version: '3'
services:
  onenav:
    image: helloz/onenav
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - './data:/data/wwwroot/default/data'
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true