version: '3'
services:
  memos:
    image: neosmemo/memos:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data:/var/opt/memos
    ports:
      - ${PANEL_APP_PORT_HTTP}:5230
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true