version: '3'
services:
  vocechat:
    image: privoce/vocechat-server:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data:/home/vocechat-server/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true